[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "Reviews"
  url = "/notes/"
  weight = 20

[[main]]
  name = "Sobre"
  url = "/about/"
  weight = 30

[[main]]
  name = "Links"
  url = "/links/"
  identifier = "Links"
  weight = 45

[[main]]
  name = "Twitch"
  url = "https://www.twitch.tv/calixtojj/"
  parent = "Links"
  weight = 10

[[main]]
  name = "YouTUbe"
  url = "https://www.youtube.com/@calixtojj"
  parent = "Links"
  weight = 20

[[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/contact/"
  weight = 50

[[main]]
  name = "<img src=\"/icons/search.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/search/"
  weight = 60